services:
  db:
    image: postgres:15
    container_name: postgres_teuzo
    restart: always
    environment:
      POSTGRES_DB: teuzo_db
      POSTGRES_USER: teuzo
      POSTGRES_PASSWORD: minha_senha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
